<?php

declare(strict_types=1);

namespace App\Presenters;

use App\Front\Components\IModalControlFactory;
use App\Front\Components\ISignInFormControlFactory;
use App\Front\Components\ModalControl;
use App\Front\Components\SignInFormControl;
use App\Model\Orm\Orm;
use Nette;
use Nette\Database\Context;
use Tracy\Debugger;


class BasePresenter extends Nette\Application\UI\Presenter
{

	/** @var  Orm @inject */
	public $orm;

	/** @var  Context @inject */
	public $database;

	/** @var IModalControlFactory @inject */
	public $modalControlFactory;

	/** @var boolean */
	public $showModal = FALSE;


	public function startup()
	{
		parent::startup(); // TODO: Change the autogenerated stub
	}


	public function beforeRender()
	{
		parent::beforeRender();
	}


	protected function createComponentModal(): ModalControl
	{
		return $this->modalControlFactory->create();
	}


	public function flashSuccess($msg)
	{
		$this->flashMessage($msg, 'success');
	}

	public function flashDanger($msg)
	{
		$this->flashMessage($msg, 'error');
	}

}
